apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: evenx-website-ingress
  namespace: evenx-dev
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "evenx-website-ip"
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/managed-certificates: "evenx-website-cert"
    networking.gke.io/v1beta1-frontend-config: "evenx-website-frontend-config"
spec:
  rules:
  - host: evenx.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: evenx-website-service
            port:
              number: 80
