apiVersion: v1
kind: Service
metadata:
  name: evenx-website-service
  namespace: evenx-prod
  labels:
    app: evenx-website
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: evenx-website
